trigger: [wf-tchh]
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
  - script: |
      npm install
      npm run build-wftchh
    displayName: 'Quasar Build'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dist/spa'
      artifact: 'dist-spa'
      publishLocation: 'pipeline'
